name: challange_kide
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.4 <4.0.0"

dependencies:
  http: ^1.2.2
  google_fonts: ^6.2.1
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  salomon_bottom_bar: ^3.3.2
  go_router: ^14.2.3
  flutter_secure_storage: ^9.2.2
  process_run: ^0.12.0
  shared_preferences: ^2.0.15
  image_picker: ^1.0.0
  video_player: ^2.6.0
  appinio_video_player: ^1.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - image/kids.png
    - image/BG.png
    - image/user.png
    - image/chapterBG.png
